site_name: Dendron
site_author: Richard Kelley

repo_name: RichardKelley/dendron
repo_url: https://github.com/RichardKelley/dendron

nav:
  - 🌳 Dendron: 
    - Home: index.md
    - Installation: install.md
  - Tutorials:
    - Tutorial 1. Chat Agent:
      - Introduction - Building a Local Chat Agent with ASR and TTS Support: tutorial_intro.md
      - Part 0. A Single Node: 0_tutorial_single_node.md
      - Part 1. Thinking and Talking: 1_tutorial_seq.md
      - Part 2. Managing Chat State: 2_tutorial_implicit_seq.md
      - Part 3. Learning How to Say Goodbye: 3_tutorial_llm_conditional.md
      - Part 4. Chat with TTS and ASR: 4_tutorial_tts_asr_chat.md
  - API Reference:
    - Action Nodes:
      - api/actions/always_failure.md
      - api/actions/always_success.md
      - api/actions/async_action.md
      - api/actions/causal_lm_action.md
      - api/actions/image_lm_action.md
      - api/actions/pipeline_action.md
      - api/actions/simple_action.md
      - api/actions/generate_action.md
      - api/actions/loglikelihood_action.md
      - api/actions/loglikelihood_rolling_action.md
    - Configs:
      - api/configs/hflm_config.md
      - api/configs/lm_action_config.md
      - api/configs/lm_completion_config.md
    - Condition Nodes:
      - api/conditions/lm_completion_condition.md
      - api/conditions/simple_condition.md
    - Control Nodes:
      - api/controls/fallback.md
      - api/controls/sequence.md
    - Decorator Nodes:
      - api/decorators/blackboard_history.md
      - api/decorators/force_failure.md
      - api/decorators/force_success.md
      - api/decorators/inverter.md
      - api/decorators/repeat.md
      - api/decorators/retry.md
      - api/decorators/run_once.md
      - api/decorators/timeout.md
    - api/action_node.md
    - api/basic_types.md
    - api/behavior_tree_factory.md
    - api/behavior_tree.md
    - api/blackboard.md
    - api/condition_node.md
    - api/control_node.md
    - api/decorator_node.md
    - api/tree_node.md

theme: 
  name: material
  favicon: img/favicon.ico
  logo: img/favicon.ico
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.expand
    - content.code.copy
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - search.suggest
    - search.highlight


extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - mdx_math
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


plugins:
  - glightbox
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_submodules: false 

extra:
  analytics:
    provider: google
    property: G-DSF85J64V0
